[package]
name = "rgb-lib-uniffi"
version = "0.1.0"
authors = [
    "Zoe Faltibà <zoefaltiba@gmail.com>",
    "Nicola Busanello <nicola.busanello@gmail.com>",
]
edition = "2021"
rust-version = "1.67"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "rgblibuniffi"

[[bin]]
name = "rgb-lib-uniffi-bindgen"
path = "uniffi-bindgen.rs"

[features]
default = ["uniffi/cli"]

[dependencies]
rgb-lib = { version = "0.3.0-alpha.6", path = "../../", features = [
    "electrum",
    "esplora",
] }
uniffi = { version = "0.28.0", default-features = false }

[build-dependencies]
uniffi = { version = "0.28.0", default-features = false, features = [
    "build",
] }

[target.'cfg(target_os = "android")'.dependencies]
aws-lc-rs = { version = "1.9.0", default-features = false, features = [
    "bindgen",
] }
openssl = { version = "0.10", default-features = false, features = [
    "vendored",
] }

[workspace]
