name: Format code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Format
        run: cargo fmt --all -- --check
      - name: Format c-ffi bindings
        working-directory: ./bindings/c-ffi
        run: |
          make format
          git diff --exit-code
      - name: Format uniffi bindings
        working-directory: ./bindings/uniffi
        run: cargo fmt -- --check
